import { generateId } from "@/lib/utils";
import { db } from "./index";
import { jobs, jobEvents, sources, profile, settings } from "./schema";

const mockJobs = [
  {
    id: generateId(),
    title: "Senior Software Engineer",
    company: "Nubank",
    description:
      "Estamos procurando uma pessoa engenheira de software sênior para se juntar ao time de plataforma. Você vai trabalhar com arquitetura de sistemas distribuídos, APIs REST, e contribuir para produtos que impactam milhões de usuários. Buscamos pessoas com experiência em Kotlin, Java ou linguagens da JVM, e conhecimento em sistemas de alta disponibilidade.",
    location: "São Paulo, SP",
    locationType: "hybrid" as const,
    salaryMin: 20000,
    salaryMax: 30000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "clt" as const,
    experienceLevel: "senior" as const,
    technologies: ["Kotlin", "Java", "Kafka", "Kubernetes", "AWS", "PostgreSQL"],
    tags: ["fintech", "plataforma", "alto impacto"],
    source: "linkedin" as const,
    sourceId: "nubank-sse-2024-001",
    url: "https://www.linkedin.com/jobs/view/1",
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Full Stack Developer (React + Node)",
    company: "Vercel",
    description:
      "We're looking for a full stack developer to join our platform engineering team. You'll work on developer tooling, build and deploy systems, and help shape the future of web development. Strong experience with React, Next.js, TypeScript, and Node.js required. Remote-first culture.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 140,
    salaryMax: 200,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "senior" as const,
    technologies: ["React", "Next.js", "TypeScript", "Node.js", "Go", "Rust"],
    tags: ["developer-tools", "platform", "remote"],
    source: "remoteok" as const,
    sourceId: "vercel-fsd-2024-002",
    url: "https://remoteok.com/remote-jobs/vercel-full-stack-developer",
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Data Scientist - Credit Risk",
    company: "Itaú Unibanco",
    description:
      "Atuar no time de risco de crédito pessoa física, desenvolvendo modelos preditivos e estratégias de concessão. Você vai trabalhar com grandes volumes de dados, modelagem estatística e machine learning para tomada de decisão. Buscamos profissionais com forte background em estatística, Python e SQL.",
    location: "São Paulo, SP",
    locationType: "hybrid" as const,
    salaryMin: 15000,
    salaryMax: 25000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "clt" as const,
    experienceLevel: "senior" as const,
    technologies: ["Python", "SQL", "Machine Learning", "Scikit-learn", "PySpark", "AWS"],
    tags: ["fintech", "risco", "modelagem"],
    source: "linkedin" as const,
    sourceId: "itau-ds-2024-003",
    url: "https://www.linkedin.com/jobs/view/2",
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Frontend Engineer - Design System",
    company: "Linear",
    description:
      "Help us build and maintain Linear's design system and component library. You'll work closely with designers to create polished, accessible, and performant UI components. Strong eye for detail, experience with React, TypeScript, and animation libraries required.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 150,
    salaryMax: 220,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "senior" as const,
    technologies: ["React", "TypeScript", "Framer Motion", "Radix UI", "CSS"],
    tags: ["design-system", "ui", "remote"],
    source: "remoteok" as const,
    sourceId: "linear-fe-2024-004",
    url: "https://remoteok.com/remote-jobs/linear-frontend-engineer",
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Estágio em Engenharia de Software",
    company: "Google",
    description:
      "O programa de estágio do Google oferece a oportunidade de trabalhar em projetos reais com engenheiros experientes. Você vai contribuir para produtos usados por bilhões de pessoas. Buscamos estudantes de ciência da computação, engenharia ou áreas relacionadas com conclusão prevista entre 2026 e 2027.",
    location: "São Paulo, SP",
    locationType: "onsite" as const,
    salaryMin: 5000,
    salaryMax: 8000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "internship" as const,
    experienceLevel: "internship" as const,
    technologies: ["Python", "C++", "Java", "Data Structures", "Algorithms"],
    tags: ["big-tech", "estágio", "estudante"],
    source: "linkedin" as const,
    sourceId: "google-estagio-2024-005",
    url: "https://www.linkedin.com/jobs/view/3",
    postedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Desenvolvedor Python Pleno",
    company: "Trybe",
    description:
      "Buscamos uma pessoa desenvolvedora Python pleno para o time de plataforma. Você vai trabalhar com desenvolvimento de APIs REST, integrações com serviços externos, e manutenção de pipelines de dados. Conhecimento em Django ou FastAPI, PostgreSQL e Docker é essencial.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 8000,
    salaryMax: 12000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "clt" as const,
    experienceLevel: "mid" as const,
    technologies: ["Python", "Django", "FastAPI", "PostgreSQL", "Docker", "Redis"],
    tags: ["edtech", "plataforma", "remoto"],
    source: "linkedin" as const,
    sourceId: "trybe-py-2024-006",
    url: "https://www.linkedin.com/jobs/view/4",
    postedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Product Manager - Developer Experience",
    company: "GitHub",
    description:
      "We're looking for a product manager to own the developer experience for GitHub Actions and CI/CD products. You'll define strategy, work with engineering and design, and ship products that millions of developers use daily. Technical background and developer tooling experience preferred.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 160,
    salaryMax: 240,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "senior" as const,
    technologies: ["CI/CD", "Developer Tools", "APIs", "Platform"],
    tags: ["developer-tools", "product", "remote"],
    source: "remoteok" as const,
    sourceId: "github-pm-2024-007",
    url: "https://remoteok.com/remote-jobs/github-product-manager",
    postedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Cientista de Dados Júnior",
    company: "Stone",
    description:
      "Junte-se ao time de dados da Stone para desenvolver modelos de machine learning, criar dashboards e analisar padrões de transações. Você vai trabalhar com Python, SQL e ferramentas de visualização. Ótima oportunidade para quem está começando na área de dados.",
    location: "Rio de Janeiro, RJ",
    locationType: "hybrid" as const,
    salaryMin: 6000,
    salaryMax: 9000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "clt" as const,
    experienceLevel: "junior" as const,
    technologies: ["Python", "SQL", "Pandas", "Scikit-learn", "Metabase"],
    tags: ["fintech", "dados", "junior"],
    source: "linkedin" as const,
    sourceId: "stone-ds-2024-008",
    url: "https://www.linkedin.com/jobs/view/5",
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Staff Engineer - Core Infrastructure",
    company: "Railway",
    description:
      "Looking for a staff engineer to lead our core infrastructure team. You'll design and build the platform that powers thousands of deployments. Deep experience with distributed systems, Kubernetes, and cloud infrastructure required. This is a high-impact role shaping the future of deployment infrastructure.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 180,
    salaryMax: 260,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "lead" as const,
    technologies: ["Go", "Kubernetes", "Terraform", "AWS", "Distributed Systems"],
    tags: ["infrastructure", "platform", "remote"],
    source: "remoteok" as const,
    sourceId: "railway-staff-2024-009",
    url: "https://remoteok.com/remote-jobs/railway-staff-engineer",
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Desenvolvedor Node.js Sênior",
    company: "Ifood",
    description:
      "Buscamos engenheiro de software sênior com foco em backend Node.js. Você vai projetar e implementar sistemas escaláveis, APIs REST e GraphQL, e contribuir para a arquitetura de microsserviços que processa milhões de pedidos por dia. Experiência com AWS, bancos relacionais e mensageria é necessária.",
    location: "São Paulo, SP",
    locationType: "hybrid" as const,
    salaryMin: 18000,
    salaryMax: 26000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "clt" as const,
    experienceLevel: "senior" as const,
    technologies: ["Node.js", "TypeScript", "GraphQL", "AWS", "PostgreSQL", "Redis"],
    tags: ["delivery", "high-scale", "backend"],
    source: "linkedin" as const,
    sourceId: "ifood-node-2024-010",
    url: "https://www.linkedin.com/jobs/view/6",
    postedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Data Engineer",
    company: "QuintoAndar",
    description:
      "Você vai construir e manter pipelines de dados que alimentam produtos e decisões em toda a empresa. Buscamos profissionais com experiência em Python, SQL, ferramentas de orquestração e cloud. Você trabalhará com time de dados, produto e engenharia.",
    location: "São Paulo, SP",
    locationType: "hybrid" as const,
    salaryMin: 12000,
    salaryMax: 18000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "clt" as const,
    experienceLevel: "mid" as const,
    technologies: ["Python", "SQL", "Airflow", "Spark", "AWS", "dbt"],
    tags: ["proptech", "dados", "pipelines"],
    source: "linkedin" as const,
    sourceId: "quintoandar-de-2024-011",
    url: "https://www.linkedin.com/jobs/view/7",
    postedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Senior Frontend Engineer - Design Tools",
    company: "Figma",
    description:
      "Join the Figma editor team to build the future of collaborative design. You'll work on the core rendering engine, plugin APIs, and real-time collaboration features. Deep expertise in web graphics, WebGL, or Canvas APIs is a plus. Remote-friendly with offices in SF and NYC.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 170,
    salaryMax: 250,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "senior" as const,
    technologies: ["TypeScript", "WebGL", "Canvas", "React", "C++", "WASM"],
    tags: ["design-tools", "graphics", "remote"],
    source: "remoteok" as const,
    sourceId: "figma-fe-2024-012",
    url: "https://remoteok.com/remote-jobs/figma-senior-frontend",
    postedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Desenvolvedor Full Stack Júnior",
    company: "Cora",
    description:
      "Procuramos desenvolvedor full stack júnior para o time de produtos. Você vai trabalhar com React, TypeScript, Node.js e contribuir para features do app de gestão financeira para PJ. Ótima oportunidade para aprender e crescer em um ambiente de alta performance.",
    location: "São Paulo, SP",
    locationType: "onsite" as const,
    salaryMin: 5000,
    salaryMax: 7000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "clt" as const,
    experienceLevel: "junior" as const,
    technologies: ["React", "TypeScript", "Node.js", "PostgreSQL", "React Native"],
    tags: ["fintech", "junior", "presencial"],
    source: "linkedin" as const,
    sourceId: "cora-fs-2024-013",
    url: "https://www.linkedin.com/jobs/view/8",
    postedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "DevOps Engineer",
    company: "Render",
    description:
      "We're hiring a DevOps engineer to build and maintain our cloud platform. You'll work on infrastructure automation, CI/CD pipelines, monitoring, and incident response. If you love building reliable systems and have experience with Kubernetes, Terraform, and cloud providers, we want to talk.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 130,
    salaryMax: 190,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "mid" as const,
    technologies: ["Kubernetes", "Terraform", "AWS", "Docker", "Go", "Prometheus"],
    tags: ["infrastructure", "cloud", "remote"],
    source: "remoteok" as const,
    sourceId: "render-devops-2024-014",
    url: "https://remoteok.com/remote-jobs/render-devops-engineer",
    postedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Engenheiro de Machine Learning",
    company: "Suno",
    description:
      "Junte-se ao time de ML da Suno para desenvolver e deployar modelos generativos de áudio. Você vai trabalhar em modelos state-of-the-art, pipelines de treinamento, e infraestrutura de inferência. Background em deep learning, NLP e sistemas distribuídos é essencial.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 25000,
    salaryMax: 40000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "pj" as const,
    experienceLevel: "senior" as const,
    technologies: ["Python", "PyTorch", "Transformers", "CUDA", "MLOps", "AWS"],
    tags: ["IA", "audio", "generative"],
    source: "linkedin" as const,
    sourceId: "suno-mle-2024-015",
    url: "https://www.linkedin.com/jobs/view/9",
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Analytics Engineer",
    company: "Dbt Labs",
    description:
      "Help us build the modern data stack. As an analytics engineer at dbt Labs, you'll work on the dbt product, community, and internal data systems. Strong SQL skills, experience with dbt, and a passion for data modeling and analytics are required.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 120,
    salaryMax: 170,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "mid" as const,
    technologies: ["SQL", "dbt", "Snowflake", "Python", "Data Modeling"],
    tags: ["data", "analytics", "remote"],
    source: "remoteok" as const,
    sourceId: "dbtlabs-ae-2024-016",
    url: "https://remoteok.com/remote-jobs/dbt-labs-analytics-engineer",
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Engenheiro de Dados Pleno",
    company: "PicPay",
    description:
      "Você será responsável por projetar, construir e manter pipelines de dados em larga escala. Trabalhará com times de produto e analytics para viabilizar decisões baseadas em dados. Conhecimento em Python, SQL, Spark e cloud é necessário.",
    location: "São Paulo, SP",
    locationType: "hybrid" as const,
    salaryMin: 10000,
    salaryMax: 15000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "clt" as const,
    experienceLevel: "mid" as const,
    technologies: ["Python", "SQL", "Spark", "Airflow", "AWS", "Kafka"],
    tags: ["fintech", "dados", "pleno"],
    source: "linkedin" as const,
    sourceId: "picpay-de-2024-017",
    url: "https://www.linkedin.com/jobs/view/10",
    postedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Engineering Manager - Platform",
    company: "WorkOS",
    description:
      "Lead a team of platform engineers building APIs and SDKs that power enterprise features for thousands of applications. You'll split your time between people management, technical strategy, and hands-on coding. Experience with Node.js, TypeScript, and APIs required.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 190,
    salaryMax: 270,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "lead" as const,
    technologies: ["Node.js", "TypeScript", "APIs", "PostgreSQL", "Redis"],
    tags: ["platform", "management", "remote"],
    source: "remoteok" as const,
    sourceId: "workos-em-2024-018",
    url: "https://remoteok.com/remote-jobs/workos-engineering-manager",
    postedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Software Engineer Intern",
    company: "Stripe",
    description:
      "Join Stripe for a 12-week internship building software that powers the internet economy. You'll work on real projects with mentorship from experienced engineers. Currently pursuing a degree in CS or related field. Strong programming fundamentals required.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 8000,
    salaryMax: 11000,
    currency: "USD",
    salaryPeriod: "monthly" as const,
    contractType: "internship" as const,
    experienceLevel: "internship" as const,
    technologies: ["Python", "Java", "JavaScript", "SQL", "APIs"],
    tags: ["fintech", "internship", "remote"],
    source: "remoteok" as const,
    sourceId: "stripe-intern-2024-019",
    url: "https://remoteok.com/remote-jobs/stripe-software-engineer-intern",
    postedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Desenvolvedor React Native Pleno",
    company: "Loggi",
    description:
      "Buscamos desenvolvedor React Native pleno para o time mobile. Você vai trabalhar no app da Loggi usado por milhares de entregadores e clientes. Experiência com React Native, TypeScript e integração com APIs REST é essencial. Conhecimento em performance mobile é diferencial.",
    location: "São Paulo, SP",
    locationType: "hybrid" as const,
    salaryMin: 9000,
    salaryMax: 14000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "clt" as const,
    experienceLevel: "mid" as const,
    technologies: ["React Native", "TypeScript", "React", "APIs REST", "iOS", "Android"],
    tags: ["logistics", "mobile", "pleno"],
    source: "linkedin" as const,
    sourceId: "loggi-rn-2024-020",
    url: "https://www.linkedin.com/jobs/view/11",
    postedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Platform Engineer - Developer Experience",
    company: "Supabase",
    description:
      "Help us build the developer experience for Supabase. You'll work on our client libraries, CLI tools, and documentation. We're looking for someone who cares deeply about developer workflows, has strong TypeScript skills, and wants to make database access delightful.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 140,
    salaryMax: 200,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "senior" as const,
    technologies: ["TypeScript", "PostgreSQL", "Node.js", "React", "CLI"],
    tags: ["developer-tools", "database", "remote"],
    source: "remoteok" as const,
    sourceId: "supabase-pe-2024-021",
    url: "https://remoteok.com/remote-jobs/supabase-platform-engineer",
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Analista de Dados Sênior",
    company: "Mercado Libre",
    description:
      "Junte-se ao time de dados do Mercado Libre para análises estratégicas que impactam milhões de usuários. Você vai criar dashboards, análises de funil, experimentos A/B e recomendações baseadas em dados. Forte conhecimento em SQL, Python e visualização de dados é necessário.",
    location: "São Paulo, SP",
    locationType: "hybrid" as const,
    salaryMin: 14000,
    salaryMax: 20000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "clt" as const,
    experienceLevel: "senior" as const,
    technologies: ["SQL", "Python", "Tableau", "A/B Testing", "Statistics", "BigQuery"],
    tags: ["ecommerce", "analytics", "senior"],
    source: "linkedin" as const,
    sourceId: "ml-analytics-2024-022",
    url: "https://www.linkedin.com/jobs/view/12",
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Backend Engineer - Rust",
    company: "Cloudflare",
    description:
      "Build the future of the Internet with Cloudflare. We're looking for backend engineers to work on our edge network, DDoS protection, and performance products. Strong systems programming skills in Rust or C++ required. Experience with networking, distributed systems, and performance optimization.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 150,
    salaryMax: 220,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "senior" as const,
    technologies: ["Rust", "C++", "Networking", "Distributed Systems", "Linux"],
    tags: ["infrastructure", "security", "remote"],
    source: "remoteok" as const,
    sourceId: "cloudflare-be-2024-023",
    url: "https://remoteok.com/remote-jobs/cloudflare-backend-engineer",
    postedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Trainee em Engenharia de Software",
    company: "BTG Pactual",
    description:
      "Programa de trainee em engenharia de software do maior banco de investimentos da América Latina. Você vai rodar por diferentes squads de tecnologia, aprender sobre mercado financeiro e contribuir para sistemas críticos. Formação em ciência da computação, engenharia ou estatística até 2025.",
    location: "São Paulo, SP",
    locationType: "onsite" as const,
    salaryMin: 8000,
    salaryMax: 10000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "clt" as const,
    experienceLevel: "trainee" as const,
    technologies: ["Python", "Java", "SQL", "AWS"],
    tags: ["banco", "trainee", "mercado-financeiro"],
    source: "linkedin" as const,
    sourceId: "btg-trainee-2024-024",
    url: "https://www.linkedin.com/jobs/view/13",
    postedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Founding Frontend Engineer",
    company: "Raycast",
    description:
      "Join us as a founding frontend engineer to build the extension platform and developer experience. You'll work on the extension API, the store, and tooling that enables thousands of developers to extend Raycast. Strong TypeScript, React, and API design skills required.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 160,
    salaryMax: 230,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "senior" as const,
    technologies: ["TypeScript", "React", "Node.js", "APIs", "CLI"],
    tags: ["developer-tools", "extensions", "remote"],
    source: "remoteok" as const,
    sourceId: "raycast-fe-2024-025",
    url: "https://remoteok.com/remote-jobs/raycast-founding-frontend",
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Desenvolvedor Go Pleno",
    company: "Globo",
    description:
      "Você vai trabalhar no time de plataforma de conteúdo da Globo, construindo APIs e microsserviços que entregam conteúdo para milhões de brasileiros. Experiência com Go, bancos relacionais e mensageria é obrigatória. Conhecimento em sistemas de alta disponibilidade é diferencial.",
    location: "Rio de Janeiro, RJ",
    locationType: "hybrid" as const,
    salaryMin: 11000,
    salaryMax: 16000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "clt" as const,
    experienceLevel: "mid" as const,
    technologies: ["Go", "PostgreSQL", "Kafka", "Redis", "Docker", "GCP"],
    tags: ["media", "plataforma", "pleno"],
    source: "linkedin" as const,
    sourceId: "globo-go-2024-026",
    url: "https://www.linkedin.com/jobs/view/14",
    postedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "AI Engineer - LLM Infrastructure",
    company: "Anthropic",
    description:
      "Help us build the infrastructure that powers Claude and our AI research. You'll work on training infrastructure, inference optimization, and developer tooling for large language models. Deep experience with Python, distributed computing, and ML infrastructure is required.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 200,
    salaryMax: 300,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "senior" as const,
    technologies: ["Python", "PyTorch", "Kubernetes", "CUDA", "Ray", "AWS"],
    tags: ["AI", "infrastructure", "remote"],
    source: "remoteok" as const,
    sourceId: "anthropic-ai-2024-027",
    url: "https://remoteok.com/remote-jobs/anthropic-ai-engineer",
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Engenheiro de Software - Plataforma de Dados",
    company: "Amazon Web Services",
    description:
      "Desenvolva serviços de dados na AWS que atendem milhões de clientes globalmente. Você vai trabalhar em bancos de dados gerenciados, analytics e serviços de IA. Buscamos engenheiros com experiência em sistemas distribuídos, C++, Java ou Rust.",
    location: "São Paulo, SP",
    locationType: "onsite" as const,
    salaryMin: 22000,
    salaryMax: 32000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "clt" as const,
    experienceLevel: "senior" as const,
    technologies: ["C++", "Java", "Rust", "Distributed Systems", "AWS"],
    tags: ["big-tech", "cloud", "sistemas-distribuidos"],
    source: "linkedin" as const,
    sourceId: "aws-sde-2024-028",
    url: "https://www.linkedin.com/jobs/view/15",
    postedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Full Stack Developer - Growth",
    company: "Notion",
    description:
      "Join Notion's growth engineering team to build features that drive user acquisition, activation, and retention. You'll work across the stack — frontend, backend, and infrastructure — to run experiments and ship product improvements that impact millions of users.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 150,
    salaryMax: 210,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "mid" as const,
    technologies: ["TypeScript", "React", "Node.js", "PostgreSQL", "A/B Testing"],
    tags: ["productivity", "growth", "remote"],
    source: "remoteok" as const,
    sourceId: "notion-growth-2024-029",
    url: "https://remoteok.com/remote-jobs/notion-full-stack-growth",
    postedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Desenvolvedor C# .NET Pleno",
    company: "TOTVS",
    description:
      "Buscamos desenvolvedor .NET pleno para o time de produtos ERP. Você vai trabalhar em sistemas empresariais complexos, integrações e APIs. Conhecimento em C#, .NET Core, SQL Server e práticas de arquitetura de software é necessário.",
    location: "São Paulo, SP",
    locationType: "hybrid" as const,
    salaryMin: 8000,
    salaryMax: 12000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "clt" as const,
    experienceLevel: "mid" as const,
    technologies: ["C#", ".NET Core", "SQL Server", "Azure", "APIs REST"],
    tags: ["ERP", "enterprise", "pleno"],
    source: "linkedin" as const,
    sourceId: "totvs-csharp-2024-030",
    url: "https://www.linkedin.com/jobs/view/16",
    postedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Solutions Engineer - API",
    company: "Stripe",
    description:
      "Help Stripe users build and scale their businesses. As a solutions engineer, you'll work with developers to design integrations, troubleshoot issues, and share best practices. Strong technical background with experience in APIs, web development, and payments preferred.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 130,
    salaryMax: 180,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "mid" as const,
    technologies: ["APIs", "Python", "JavaScript", "Payments", "Cloud"],
    tags: ["fintech", "solutions", "remote"],
    source: "remoteok" as const,
    sourceId: "stripe-se-2024-031",
    url: "https://remoteok.com/remote-jobs/stripe-solutions-engineer",
    postedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Engenheiro de Dados Sênior",
    company: "Netflix",
    description:
      "Junte-se ao time de dados da Netflix para construir a infraestrutura de dados que suporta decisões de conteúdo, marketing e produto globalmente. Você vai trabalhar com pipelines em larga escala, data lakes e ferramentas de analytics. Experiência com Spark, Flink e cloud é essencial.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 22000,
    salaryMax: 35000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "pj" as const,
    experienceLevel: "senior" as const,
    technologies: ["Spark", "Flink", "Python", "AWS", "Iceberg", "Kafka"],
    tags: ["streaming", "dados", "big-data"],
    source: "linkedin" as const,
    sourceId: "netflix-de-2024-032",
    url: "https://www.linkedin.com/jobs/view/17",
    postedAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Design Engineer",
    company: "Linear",
    description:
      "We're looking for a design engineer who straddles the line between design and engineering. You'll build UI components, implement designs with precision, and contribute to our design system. Strong CSS, React, and animation skills. An eye for detail is non-negotiable.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 140,
    salaryMax: 200,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "senior" as const,
    technologies: ["React", "TypeScript", "CSS", "Framer Motion", "Figma"],
    tags: ["design", "ui", "remote"],
    source: "remoteok" as const,
    sourceId: "linear-de-2024-033",
    url: "https://remoteok.com/remote-jobs/linear-design-engineer",
    postedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Desenvolvedor Java Sênior - Microsserviços",
    company: "Creditas",
    description:
      "Buscamos engenheiro Java sênior para arquitetar e desenvolver microsserviços em plataforma de crédito. Você vai trabalhar com Spring Boot, Kafka, bancos relacionais e cloud. Experiência em sistemas financeiros e alta disponibilidade é valorizada.",
    location: "São Paulo, SP",
    locationType: "hybrid" as const,
    salaryMin: 16000,
    salaryMax: 24000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "clt" as const,
    experienceLevel: "senior" as const,
    technologies: ["Java", "Spring Boot", "Kafka", "PostgreSQL", "AWS", "Docker"],
    tags: ["fintech", "backend", "senior"],
    source: "linkedin" as const,
    sourceId: "creditas-java-2024-034",
    url: "https://www.linkedin.com/jobs/view/18",
    postedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Infrastructure Engineer",
    company: "Fly.io",
    description:
      "Help us build the edge infrastructure that powers global applications. You'll work on our VM orchestration, networking layer, and developer tooling. Deep Linux kernel knowledge, experience with distributed systems, and a love for infrastructure as code required.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 150,
    salaryMax: 220,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "senior" as const,
    technologies: ["Go", "Linux", "Firecracker", "Networking", "Distributed Systems"],
    tags: ["infrastructure", "edge", "remote"],
    source: "remoteok" as const,
    sourceId: "flyio-ie-2024-035",
    url: "https://remoteok.com/remote-jobs/fly-infrastructure-engineer",
    postedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Estágio em Ciência de Dados",
    company: "Kognit",
    description:
      "Procuramos estagiário de ciência de dados para trabalhar com modelos preditivos, análise exploratória e visualização de dados. Você vai aprender na prática com mentores experientes. Conhecimento em Python, SQL e estatística básica é desejável.",
    location: "São Paulo, SP",
    locationType: "onsite" as const,
    salaryMin: 2500,
    salaryMax: 3500,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "internship" as const,
    experienceLevel: "internship" as const,
    technologies: ["Python", "SQL", "Pandas", "Matplotlib", "Statistics"],
    tags: ["dados", "estágio", "estudante"],
    source: "linkedin" as const,
    sourceId: "kognit-estagio-2024-036",
    url: "https://www.linkedin.com/jobs/view/19",
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Senior Site Reliability Engineer",
    company: "Datadog",
    description:
      "Join Datadog's SRE team to ensure the reliability and performance of our monitoring platform. You'll build automation, respond to incidents, and improve system resilience. Strong experience with cloud infrastructure, observability tools, and coding in Go or Python required.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 160,
    salaryMax: 230,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "senior" as const,
    technologies: ["Go", "Python", "Kubernetes", "Terraform", "Prometheus", "AWS"],
    tags: ["observability", "sre", "remote"],
    source: "remoteok" as const,
    sourceId: "datadog-sre-2024-037",
    url: "https://remoteok.com/remote-jobs/datadog-senior-sre",
    postedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Desenvolvedor Frontend React Pleno",
    company: "VTEX",
    description:
      "Você vai trabalhar no desenvolvimento do store framework da VTEX, a plataforma de e-commerce líder na América Latina. Buscamos profissional com experiência em React, TypeScript e performance web. Conhecimento em Next.js e ferramentas de build é diferencial.",
    location: "São Paulo, SP",
    locationType: "hybrid" as const,
    salaryMin: 10000,
    salaryMax: 15000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "clt" as const,
    experienceLevel: "mid" as const,
    technologies: ["React", "TypeScript", "Next.js", "GraphQL", "Performance"],
    tags: ["ecommerce", "frontend", "pleno"],
    source: "linkedin" as const,
    sourceId: "vtex-react-2024-038",
    url: "https://www.linkedin.com/jobs/view/20",
    postedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Database Reliability Engineer",
    company: "PlanetScale",
    description:
      "Help us build the world's most reliable MySQL-compatible serverless database platform. You'll work on query optimization, replication, backup strategies, and incident response. Deep MySQL knowledge and experience with large-scale database operations required.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 150,
    salaryMax: 210,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "senior" as const,
    technologies: ["MySQL", "Go", "Vitess", "Kubernetes", "Linux"],
    tags: ["database", "infrastructure", "remote"],
    source: "remoteok" as const,
    sourceId: "planetscale-dre-2024-039",
    url: "https://remoteok.com/remote-jobs/planetscale-database-reliability",
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Pessoa Desenvolvedora Full Stack Sênior",
    company: "Dr. Consulta",
    description:
      "Buscamos engenheiro de software sênior full stack para o time de produtos de saúde. Você vai trabalhar com React, Node.js e cloud para construir features que melhoram o acesso à saúde no Brasil. Experiência com arquitetura de sistemas, testes e entregas contínuas é essencial.",
    location: "São Paulo, SP",
    locationType: "hybrid" as const,
    salaryMin: 15000,
    salaryMax: 22000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "clt" as const,
    experienceLevel: "senior" as const,
    technologies: ["React", "Node.js", "TypeScript", "PostgreSQL", "AWS", "Docker"],
    tags: ["healthtech", "fullstack", "senior"],
    source: "linkedin" as const,
    sourceId: "drconsulta-fs-2024-040",
    url: "https://www.linkedin.com/jobs/view/21",
    postedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Developer Advocate - AI/ML",
    company: "Replicate",
    description:
      "Help developers succeed with AI. You'll create tutorials, documentation, and example projects, speak at conferences, and engage with the community. Strong technical background in ML/AI, excellent communication skills, and experience with Python and web development.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 130,
    salaryMax: 180,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "mid" as const,
    technologies: ["Python", "Machine Learning", "APIs", "Documentation", "Community"],
    tags: ["developer-relations", "AI", "remote"],
    source: "remoteok" as const,
    sourceId: "replicate-da-2024-041",
    url: "https://remoteok.com/remote-jobs/replicate-developer-advocate",
    postedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Engenheiro de QA Automation",
    company: "Conta Simples",
    description:
      "Você vai construir e manter a infraestrutura de testes automatizados da Conta Simples. Responsável por estratégias de teste, frameworks de automação e qualidade de entregas. Experiência com Cypress, Playwright ou ferramentas similares é necessária.",
    location: "São Paulo, SP",
    locationType: "hybrid" as const,
    salaryMin: 7000,
    salaryMax: 11000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "clt" as const,
    experienceLevel: "mid" as const,
    technologies: ["Cypress", "Playwright", "TypeScript", "Node.js", "CI/CD"],
    tags: ["fintech", "qa", "automacao"],
    source: "linkedin" as const,
    sourceId: "contasimples-qa-2024-042",
    url: "https://www.linkedin.com/jobs/view/22",
    postedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Protocol Engineer - Blockchain",
    company: "Helium",
    description:
      "Build the decentralized wireless network. You'll work on the Helium protocol, consensus mechanisms, and blockchain infrastructure. Experience with Rust, distributed systems, and blockchain protocols required. Remote-first team with global impact.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 170,
    salaryMax: 250,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "senior" as const,
    technologies: ["Rust", "Blockchain", "Distributed Systems", "Cryptography", "P2P"],
    tags: ["web3", "infrastructure", "remote"],
    source: "remoteok" as const,
    sourceId: "helium-pe-2024-043",
    url: "https://remoteok.com/remote-jobs/helium-protocol-engineer",
    postedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Analista de Business Intelligence",
    company: "Natura",
    description:
      "Atuar no time de BI da Natura, criando dashboards, relatórios e análises que apoiam decisões estratégicas. Você vai trabalhar com SQL, Power BI e ferramentas de cloud. Conhecimento em Python para análise de dados é diferencial.",
    location: "São Paulo, SP",
    locationType: "hybrid" as const,
    salaryMin: 7000,
    salaryMax: 10000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "clt" as const,
    experienceLevel: "mid" as const,
    technologies: ["SQL", "Power BI", "Python", "Snowflake", "dbt"],
    tags: ["cosmetics", "analytics", "bi"],
    source: "linkedin" as const,
    sourceId: "natura-bi-2024-044",
    url: "https://www.linkedin.com/jobs/view/23",
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Security Engineer - Application Security",
    company: "1Password",
    description:
      "Help us keep millions of users' secrets safe. You'll work on application security, penetration testing, security reviews, and building security tooling. Strong understanding of web security, cryptography, and secure coding practices required.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 140,
    salaryMax: 200,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "senior" as const,
    technologies: ["Security", "Cryptography", "Go", "TypeScript", "AWS"],
    tags: ["security", "infrastructure", "remote"],
    source: "remoteok" as const,
    sourceId: "1password-se-2024-045",
    url: "https://remoteok.com/remote-jobs/1password-security-engineer",
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Desenvolvedor Elixir Pleno",
    company: "Pipefy",
    description:
      "Buscamos desenvolvedor Elixir pleno para o time de plataforma. Você vai trabalhar com Phoenix, Absinthe (GraphQL) e bancos relacionais. Buscamos pessoas com experiência em linguagens funcionais e sistemas concorrentes.",
    location: "São Paulo, SP",
    locationType: "hybrid" as const,
    salaryMin: 9000,
    salaryMax: 14000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "clt" as const,
    experienceLevel: "mid" as const,
    technologies: ["Elixir", "Phoenix", "GraphQL", "PostgreSQL", "Redis"],
    tags: ["produtividade", "backend", "pleno"],
    source: "linkedin" as const,
    sourceId: "pipefy-elixir-2024-046",
    url: "https://www.linkedin.com/jobs/view/24",
    postedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Machine Learning Engineer - Search",
    company: "Spotify",
    description:
      "Join the search team at Spotify to build and improve ML models that power music and podcast discovery. You'll work on ranking, personalization, and query understanding. Experience with information retrieval, NLP, and large-scale ML systems required.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 160,
    salaryMax: 230,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "senior" as const,
    technologies: ["Python", "TensorFlow", "NLP", "Information Retrieval", "Kubernetes"],
    tags: ["music", "search", "AI"],
    source: "remoteok" as const,
    sourceId: "spotify-mle-2024-047",
    url: "https://remoteok.com/remote-jobs/spotify-ml-engineer-search",
    postedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Trainee em Analytics",
    company: "Ambev",
    description:
      "Programa de trainee em analytics e dados da Ambev. Você vai rodar por diferentes áreas (supply chain, marketing, vendas) aplicando ciência de dados em problemas reais. Formação em estatística, engenharia, ciência da computação ou áreas correlatas.",
    location: "São Paulo, SP",
    locationType: "onsite" as const,
    salaryMin: 7000,
    salaryMax: 9000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "clt" as const,
    experienceLevel: "trainee" as const,
    technologies: ["Python", "SQL", "R", "Statistics", "Data Visualization"],
    tags: ["beverages", "trainee", "analytics"],
    source: "linkedin" as const,
    sourceId: "ambev-trainee-2024-048",
    url: "https://www.linkedin.com/jobs/view/25",
    postedAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Developer Experience Engineer",
    company: "Railway",
    description:
      "Make deploying software delightful. You'll work on Railway's CLI, GitHub integration, documentation, and overall developer experience. Strong full-stack skills, empathy for developers, and experience with CI/CD and cloud platforms required.",
    location: "Remote",
    locationType: "remote" as const,
    salaryMin: 130,
    salaryMax: 190,
    currency: "USD",
    salaryPeriod: "yearly" as const,
    contractType: "international" as const,
    experienceLevel: "mid" as const,
    technologies: ["TypeScript", "Node.js", "React", "CLI", "Docker"],
    tags: ["developer-tools", "dx", "remote"],
    source: "remoteok" as const,
    sourceId: "railway-dx-2024-049",
    url: "https://remoteok.com/remote-jobs/railway-developer-experience",
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
  {
    id: generateId(),
    title: "Desenvolvedor PHP/Laravel Sênior",
    company: "Hotmart",
    description:
      "Buscamos engenheiro de software sênior para o time de produtos. Você vai trabalhar com PHP, Laravel e Vue.js em uma plataforma que atende milhões de criadores de conteúdo. Experiência em sistemas de alta disponibilidade, filas e cache é necessária.",
    location: "São Paulo, SP",
    locationType: "hybrid" as const,
    salaryMin: 14000,
    salaryMax: 20000,
    currency: "BRL",
    salaryPeriod: "monthly" as const,
    contractType: "clt" as const,
    experienceLevel: "senior" as const,
    technologies: ["PHP", "Laravel", "Vue.js", "Redis", "MySQL", "AWS"],
    tags: ["edtech", "backend", "senior"],
    source: "linkedin" as const,
    sourceId: "hotmart-php-2024-050",
    url: "https://www.linkedin.com/jobs/view/26",
    postedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    status: "new" as const,
  },
];

export async function seed() {
  const existing = await db.select({ id: jobs.id }).from(jobs).limit(1);
  if (existing.length > 0) {
    console.log("Database already seeded, skipping.");
    return;
  }

  for (const job of mockJobs) {
    await db.insert(jobs).values(job);
    await db.insert(jobEvents).values({
      id: generateId(),
      jobId: job.id,
      eventType: "discovered",
      description: `Vaga encontrada via ${job.source}`,
      occurredAt: new Date().toISOString(),
    });
  }

  const sourceEntries = [
    { id: generateId(), name: "LinkedIn", type: "linkedin", config: null },
    { id: generateId(), name: "Remote OK", type: "remoteok", config: null },
    { id: generateId(), name: "Importação Manual", type: "manual", config: null },
    { id: generateId(), name: "Importação CSV", type: "csv", config: null },
  ];

  for (const src of sourceEntries) {
    await db.insert(sources).values(src);
  }

  await db.insert(profile).values({
    id: "default",
    name: "Usuário",
    headline: "Full-Stack Developer & Data Scientist",
    summary: "Desenvolvedor full-stack com experiência em TypeScript, Python, Node.js e Next.js. Formação em Estatística e Data Science pela USP-ICMC.",
    skills: ["TypeScript", "Python", "Node.js", "Next.js", "React", "SQL", "PostgreSQL", "Docker", "AWS", "Machine Learning", "Data Science", "APIs REST", "Git", "Tailwind CSS"],
    desiredRoles: ["Software Engineer", "Full Stack Developer", "Data Scientist", "Tech Lead", "Platform Engineer"],
    desiredSalaryMin: 15000,
    desiredSalaryMax: 30000,
    desiredCurrency: "BRL",
    desiredLocationTypes: ["remote", "hybrid"],
    desiredContractTypes: ["clt", "pj", "international"],
    experienceLevel: "mid",
    languages: ["Português", "Inglês"],
  });

  console.log(`Seeded ${mockJobs.length} jobs, ${sourceEntries.length} sources, and profile.`);

  // Default settings
  const existingSettings = await db.select({ id: settings.id }).from(settings).limit(1);
  if (existingSettings.length === 0) {
    await db.insert(settings).values({ id: "default" });
    console.log("Default settings created.");
  }
}
